CREATE TABLE banners (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title1 VARCHAR(255) NOT NULL,
    title2 VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,

    btnTitle1 VARCHAR(255) NOT NULL DEFAULT '',
    btnLink1 VARCHAR(255) NOT NULL DEFAULT '',
    btnTitle2 VARCHAR(255) NOT NULL DEFAULT '',
    btnLink2 VARCHAR(255) NOT NULL DEFAULT '',
    bannerLink VARCHAR(255) NOT NULL DEFAULT '',

    is_active BOOLEAN DEFAULT true,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE banners
MODIFY COLUMN btnTitle1 VARCHAR(255) NULL DEFAULT NULL,
MODIFY COLUMN btnLink1 VARCHAR(255) NULL DEFAULT NULL,
MODIFY COLUMN btnTitle2 VARCHAR(255) NULL DEFAULT NULL,
MODIFY COLUMN btnLink2 VARCHAR(255) NULL DEFAULT NULL,
MODIFY COLUMN bannerLink VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE banners
ADD COLUMN second_sort_order INT NOT NULL DEFAULT 0
AFTER sort_order;